import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Button, Typography } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ width: '100vw', minHeight: "100vh" }}>
        <nav style={{ width: "100%" }}>
          <Box width="100%" padding={["1rem", "2rem", "2rem 4rem", "2rem 8rem", "2rem 12rem"]} display="flex" alignItems="center">
            <Typography fontSize="1.125rem" fontWeight="600">Rent It</Typography>

            <Box display="flex" gap="1rem" ml="auto">
              <Button variant="outlined">
                I am a tenant
              </Button>
              <Button variant="outlined">
                I am a landlord
              </Button>
            </Box>
          </Box>
        </nav>
      </main>
    </>
  )
}
