import { Google } from '@mui/icons-material'
import { Box, Button, Card, Checkbox, Divider, FormControl, FormLabel, TextField, Typography } from '@mui/material'
import { Londrina_Sketch } from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

export default function Login() {
    return (
        <>
            <Head>
                <title>Rentals</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main style={{ width: "100vw", minHeight: "100vh" }}>
                <Box
                    width="100vw"
                    minHeight={"100vh"}
                    // sx={{
                    //     bgcolor: "secondary.main",
                    //     backgroundImage: "url('https://res.cloudinary.com/dfmoqlbyl/image/upload/v1682337286/maara-ai/darkPrint_zlxrsy.svg')"
                    // }}
                    display="flex"
                    justifyContent={"center"}
                    alignItems={"center"}
                    overflow="scroll"
                >
                    <Card
                        sx={{
                            bgcolor: "secondary.light",
                            width: ["90vw", "30rem"],
                            padding: "1rem",
                            display: "flex",
                            gap: "2rem",
                            flexDirection: "column",
                            my: "auto"
                        }}
                    >
                        <Box display={"flex"} flexDirection="column" gap="1rem">
                        <Typography variant="h6" sx={{marginX: "auto"}}>Maara AI</Typography>
                        <Typography variant="h4" fontWeight="900" sx={{marginX: "auto"}}>Hi, Welcome back!</Typography>
                        <Typography variant="body1" sx={{marginX: "auto"}}>Enter your credentials to continue</Typography>
                        </Box>
                        <Button variant="contained" sx={{ width: "100%", padding: "1rem", display: "flex", gap: "1rem" }}>
                            <Google />
                            Sign in with Google
                        </Button>
                        <Box display="flex" alignItems="center" >
                            <Box height="1px" width="100%" sx={{ backgroundColor: "primary.main" }} />
                            <Typography sx={{ padding: "0.25rem" }}>OR</Typography>
                            <Box height="1px" width="100%" sx={{ backgroundColor: "primary.main" }} />
                        </Box>
                        <Typography variant="body1" marginX="auto">Sign in with Email Address</Typography>
                        <Box width="100%" display="flex" flexDirection="column" gap="1rem">
                            <TextField
                                name="email"
                                placeholder="Email"
                            />
                            <TextField
                                name="password"
                                placeholder="Password"
                            />
                        </Box>
                        <Box display="flex" justifyContent={"space-between"} alignItems="center">
                            <FormControl sx={{ display: "flex", flexDirection: "row", alignItems: "center" }}>
                                <Checkbox name="remember-me" sx={{ width: "fit-content", }} />
                                <FormLabel sx={{ width: "fit-content" }}>Remember me</FormLabel>
                            </FormControl>
                            <Link href="/">Forgot password</Link>
                        </Box>
                        <Button variant="contained" sx={{padding: "1rem"}}>Sign In</Button>
                        <Box height="1px" width="100%" sx={{ backgroundColor: "primary.main" }} />
                        <Link href="/">Don't have an account?</Link>
                    </Card>
                </Box>
            </main>
        </>
    )
}