import { Box, Button, Card, Checkbox, Divider, FormControl, FormLabel, LinearProgress, TextField, Typography } from '@mui/material'
import Head from 'next/head'
import Link from 'next/link'
import React, { useState } from 'react'
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup"
import * as yup from "yup"
import { signIn } from 'next-auth/react'
import { useRouter } from 'next/router'

const formSchema = yup.object().shape({
    email: yup.string().required(),
    password: yup.string().required(),
})

export default function Login() {
    const router = useRouter()
    const [isLoading, setIsLoading] = useState(false)

    const { handleSubmit, register, formState: { errors } } = useForm({
        defaultValues: {
            email: "",
            password: "",
        },
        mode: "onChange",
        reValidateMode: "onChange",
        resolver: yupResolver(formSchema)
    });

    async function onSubmit(values: any) {
        setIsLoading(true)
        console.log(values)
        const { email, password } = values

        const result = await signIn("credentials", {
            redirect: false,
            email,
            password,
        });

        console.log(result)

        if (result?.ok) {
            router.push("/dashboard")
        }

    }

    return (
        <>
            <Head>
                <title>Rentals</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main style={{ width: "100vw", minHeight: "100vh" }}>
                <Box
                    width="100vw"
                    minHeight={"100vh"}
                    sx={{
                        bgcolor: "primary.light",
                    }}
                    display="flex"
                    justifyContent={"center"}
                    alignItems={"center"}
                    overflow="scroll"
                >
                    <Card
                        sx={{
                            bgcolor: "white",
                            width: ["90vw", "30rem"],
                            my: "auto",
                            borderRadius: "0.75rem"
                        }}
                    >
                        <LinearProgress sx={{display: isLoading ? "block" : "none"}} />
                        <Box
                            sx={{
                                display: "flex",
                                flexDirection: "column",
                                gap: "2rem",
                                padding: "1.5rem"
                            }}
                        >
                            <Typography color="primary.dark" mx="auto">Rentals</Typography>
                            <Box display="flex" flexDirection="column">
                                <Typography color="primary.dark" mx="auto" fontSize="1.5rem" fontWeight="600">Login</Typography>
                                <Typography color="primary.dark" mx="auto" textAlign="center">Enter your credentials to continue</Typography>
                            </Box>
                            <form id="login-form" onSubmit={handleSubmit(onSubmit)}>
                                <Box width="100%" display="flex" flexDirection="column" gap="1rem">
                                    <TextField
                                        variant="outlined"
                                        {...register("email")}
                                        placeholder="Email"
                                        sx={{
                                            width: "100%"
                                        }}
                                    />
                                    <TextField
                                        variant="outlined"
                                        {...register("password")}
                                        placeholder="Password"
                                        sx={{
                                            width: "100%"
                                        }}
                                    />
                                </Box>
                            </form>
                            <Button disabled={isLoading} type="submit" form="login-form" variant="contained" sx={{ padding: "1rem" }}>Login</Button>
                            <Divider orientation="horizontal" />
                            <Link href="/" style={{ marginRight: "auto", marginLeft: "auto" }}><Typography>Don't have an account?</Typography></Link>
                        </Box>
                    </Card>
                </Box>
            </main>
        </>
    )
}