import { Box, Button, Card, Checkbox, Divider, FormControl, FormHelperText, FormLabel, LinearProgress, TextField, Typography } from '@mui/material'
import Head from 'next/head'
import Link from 'next/link'
import React, { useState } from 'react'


export default function Signup() {
    return (
        <>
            <Head>
                <title>Rentals</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main style={{ width: "100vw", minHeight: "100vh" }}>
                <Box
                    width="100vw"
                    minHeight={"100vh"}
                    sx={{
                        bgcolor: "primary.light",
                    }}
                    display="flex"
                    justifyContent={"center"}
                    alignItems={"center"}
                    overflow="scroll"
                >
                    <Typography color="primary.dark" mx="auto" sx={{mx: "auto"}}>Check your email for a link to verify your email</Typography>
                </Box>
            </main>
        </>
    )
}